<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Add</name>
   <tag></tag>
   <elementGuidId>6a74baf9-eab0-4665-a2d0-0a37a7474efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-bs-target=&quot;#staticBackdrop&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-bs-target=&quot;#staticBackdrop&quot;]</value>
      <webElementGuid>82dd3493-9892-405f-ab06-c3d947934072</webElementGuid>
   </webElementProperties>
</WebElementEntity>
