<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Submit</name>
   <tag></tag>
   <elementGuidId>3f3338a2-96a8-4401-8691-2cd2a94ee545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product_submit&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product_submit&quot;]</value>
      <webElementGuid>a93e5940-7fcc-49a2-9594-e9273bb277af</webElementGuid>
   </webElementProperties>
</WebElementEntity>
