<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Upload</name>
   <tag></tag>
   <elementGuidId>c609b68f-9585-4b65-8a76-fc782f34c15a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-img&quot;]</value>
      <webElementGuid>e325fdc5-2b06-4eab-a033-8732f62a23ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
