<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Des</name>
   <tag></tag>
   <elementGuidId>c393ae40-118b-425b-aefb-5015cfd5c4ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-description&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-description&quot;]</value>
      <webElementGuid>cd50a80d-0122-45be-9a58-1f95638553fb</webElementGuid>
   </webElementProperties>
</WebElementEntity>
