<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Price</name>
   <tag></tag>
   <elementGuidId>78e7f012-fdf5-48d9-aa5c-d1bc3a1e4f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-price&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-price&quot;]</value>
      <webElementGuid>e9295ccc-670c-4cb0-983f-36f465709778</webElementGuid>
   </webElementProperties>
</WebElementEntity>
