<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Product_Name</name>
   <tag></tag>
   <elementGuidId>54b18141-8512-4e09-82d9-3c6ab508d461</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-name&quot;]</value>
      <webElementGuid>f803f508-d0f9-443e-b5a7-429c0a96a3dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
