<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Status</name>
   <tag></tag>
   <elementGuidId>2cbcbd07-33ee-44e0-94bd-e1ab3c93d8fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-status&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-status&quot;]</value>
      <webElementGuid>19090057-7cf6-49d7-b3a7-6aca1f686382</webElementGuid>
   </webElementProperties>
</WebElementEntity>
