<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Edit</name>
   <tag></tag>
   <elementGuidId>ddd4cfb8-5579-49d8-8ff3-887ac5949cc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-bs-target=&quot;#editRole1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-bs-target=&quot;#editRole1&quot;]</value>
      <webElementGuid>6b2c9292-d2a3-4adf-8605-0fb8e153364f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
