<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Role</name>
   <tag></tag>
   <elementGuidId>427bea63-1723-418c-8f9b-566e29eebc40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pills-profile-tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pills-profile-tab&quot;]</value>
      <webElementGuid>621dc552-6010-49ae-81ad-2cfd94c20153</webElementGuid>
   </webElementProperties>
</WebElementEntity>
