<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Password_Verify_Diff</name>
   <tag></tag>
   <elementGuidId>485c3112-2a4e-4d83-9d25-645539e42e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[@id=&quot;text-show&quot;]//*[@class=&quot;text-danger&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[@id=&quot;text-show&quot;]//*[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>8f947cb2-7db9-4a35-b120-4c31de1af1bd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
