<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Home</name>
   <tag></tag>
   <elementGuidId>8795d33c-dec7-470f-a9eb-241c8d09309d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@href=&quot;/home&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@href=&quot;/home&quot;]</value>
      <webElementGuid>63875875-3b63-4d63-83e2-3733969b9181</webElementGuid>
   </webElementProperties>
</WebElementEntity>
