<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup_Denial</name>
   <tag></tag>
   <elementGuidId>daa817b8-72b4-4e0f-92c0-020ac5b9ec43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;swal2-title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;swal2-title&quot;]</value>
      <webElementGuid>4ea2e9d1-1484-49dc-b563-761f749125fe</webElementGuid>
   </webElementProperties>
</WebElementEntity>
