<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Bank</name>
   <tag></tag>
   <elementGuidId>0eecb451-1971-4a03-b780-27580b19c930</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;pills-bank-tab&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pills-bank-tab&quot;]</value>
      <webElementGuid>6f9ef96f-a2ea-498a-97c4-445812602ce7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
