<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Bank_Full_Name</name>
   <tag></tag>
   <elementGuidId>c22715bd-9a4f-446a-a66a-c1ca0f293d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;bank-full-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;bank-full-name&quot;]</value>
      <webElementGuid>e66aee7a-2d1b-4e79-b348-694d715ca256</webElementGuid>
   </webElementProperties>
</WebElementEntity>
