<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dom_Alert</name>
   <tag></tag>
   <elementGuidId>87dd2955-42bc-4014-93b2-93a85089c0b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]</value>
      <webElementGuid>a8c3df4e-c03f-4bb4-baa6-473c893eaaf3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
