<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Username</name>
   <tag></tag>
   <elementGuidId>7d51dcd6-9bdc-4a3a-ab0f-169f93fc32ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;username&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;username&quot;]</value>
      <webElementGuid>8c2a04fa-062f-479d-b0e5-51864a2ecd5d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
