<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Title_Dashboard</name>
   <tag></tag>
   <elementGuidId>ef96c96e-cc26-4058-ba64-7ec2e8292751</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>2abd1a6b-aeb6-4b56-bc8b-ad3eb0100460</webElementGuid>
   </webElementProperties>
</WebElementEntity>
