<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_CheckBox</name>
   <tag></tag>
   <elementGuidId>bbab7187-d2b3-4cc2-919b-394ad2919e5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@action=&quot;/back/user/edit&quot;]//*[@type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@action=&quot;/back/user/edit&quot;]//*[@type=&quot;checkbox&quot;]</value>
      <webElementGuid>30c67041-839b-409f-8089-f46539094865</webElementGuid>
   </webElementProperties>
</WebElementEntity>
