<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Password</name>
   <tag></tag>
   <elementGuidId>4b2e70e9-9368-4ba0-b74b-44ae8b8d9398</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@action=&quot;/back/user/edit&quot;]//*[@name=&quot;user-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@action=&quot;/back/user/edit&quot;]//*[@name=&quot;user-password&quot;]</value>
      <webElementGuid>1df039c1-84ec-4ea2-a657-439dd0936285</webElementGuid>
   </webElementProperties>
</WebElementEntity>
