<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Desc_Add_Role</name>
   <tag></tag>
   <elementGuidId>2d981b05-156e-42bd-b5c1-a3b020986bcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;swal2-html-container&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;swal2-html-container&quot;]</value>
      <webElementGuid>d501ef2f-2bfa-48fd-9a2a-76341c2720b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Setting/Role/Create/Create_01/DOM_Alert</value>
      <webElementGuid>294db208-bcf9-40da-9d16-312a4ef2c242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ebee260c-c6c5-468d-b553-19f1c58f37f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
