<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DOM_Alert</name>
   <tag></tag>
   <elementGuidId>c9c2bd93-85ee-4db5-a636-b97112f77a95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]</value>
      <webElementGuid>5f9867dc-1586-40ca-a8c3-da6f15c3a49f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
