<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Status</name>
   <tag></tag>
   <elementGuidId>6ab3f4e7-796d-438d-8215-d193f36c6640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//form[@action=&quot;/back/product/edit&quot;]//*[@name=&quot;product-status&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//form[@action=&quot;/back/product/edit&quot;]//*[@name=&quot;product-status&quot;]</value>
      <webElementGuid>3de97ef6-a2b1-49c3-94da-9d8e676539b9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
