<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Text</name>
   <tag></tag>
   <elementGuidId>df338296-e27c-4946-8296-9dbdc90178ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;tableBody&quot;]/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;tableBody&quot;]/tr/td[5]</value>
      <webElementGuid>300469e0-3f36-4b48-901c-3b3c562950ac</webElementGuid>
   </webElementProperties>
</WebElementEntity>
