<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Re_Password</name>
   <tag></tag>
   <elementGuidId>c0d4e166-696e-44c6-b302-c0bcf2f913f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;re-user-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;re-user-password&quot;]</value>
      <webElementGuid>72d256a8-4153-437e-8257-fcf736ae11d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
