<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Role</name>
   <tag></tag>
   <elementGuidId>c9863c8d-b6fc-4d62-ad56-96b52c7cdfe9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;user-role&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;user-role&quot;]</value>
      <webElementGuid>2852b455-a504-49af-8094-0ad28245e768</webElementGuid>
   </webElementProperties>
</WebElementEntity>
