<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_Success_2</name>
   <tag></tag>
   <elementGuidId>da19fef6-a444-4106-8e8e-325982757ddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//small[@id=&quot;text-show&quot;]//*[@class=&quot;text-success&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//small[@id=&quot;text-show&quot;]//*[@class=&quot;text-success&quot;]</value>
      <webElementGuid>782aee6c-50dc-49c1-8e5d-c24dcb7c8c85</webElementGuid>
   </webElementProperties>
</WebElementEntity>
