<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Product</name>
   <tag></tag>
   <elementGuidId>a5098ca1-a548-424f-ac6a-0c1ad4ca5711</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id=&quot;navbarNavDropdown&quot;]//*[@href=&quot;/product&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id=&quot;navbarNavDropdown&quot;]//*[@href=&quot;/product&quot;]</value>
      <webElementGuid>cc3b2d68-346f-400a-b674-d5ec8d219875</webElementGuid>
   </webElementProperties>
</WebElementEntity>
