<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Add_To_Cart</name>
   <tag></tag>
   <elementGuidId>cd96fc5f-7beb-4e87-ab57-da28049700aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;product-id&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;product-id&quot;]</value>
      <webElementGuid>d56d0b37-43bc-459e-9a48-19ba1e926110</webElementGuid>
   </webElementProperties>
</WebElementEntity>
