<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Search</name>
   <tag></tag>
   <elementGuidId>7306f444-cd8b-45ea-800f-fc6cef0eb320</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;searchInput&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;searchInput&quot;]</value>
      <webElementGuid>5b6be8c0-6e95-485d-994d-9121f6337949</webElementGuid>
   </webElementProperties>
</WebElementEntity>
