<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Dom_Left_Menu</name>
   <tag></tag>
   <elementGuidId>f0715edf-1176-4dcf-90d9-3708a4751f1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;offcanvasWithBothOptions&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;offcanvasWithBothOptions&quot;]</value>
      <webElementGuid>0b01eb97-f02a-4c11-bc7d-db6939e04f2d</webElementGuid>
   </webElementProperties>
</WebElementEntity>
