<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Category_Name</name>
   <tag></tag>
   <elementGuidId>b2fedd83-e94d-41f7-a8a4-017b1dc05933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@value=&quot;${dynamicValue}&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value=&quot;${dynamicValue}&quot;]</value>
      <webElementGuid>8e185641-8935-488c-99ae-4bf1bc08ab12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Setting/Category/Edit/DOM_Edit_Category</value>
      <webElementGuid>292d9e21-55b8-492b-86dd-f2650aabf023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element_is_shadow_root</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5e2995f5-dc00-480d-8e3b-b51187289db3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
