<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Category_Name</name>
   <tag></tag>
   <elementGuidId>ec879f90-8284-4713-b1ca-47e091133d78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;category-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;category-name&quot;]</value>
      <webElementGuid>0eb9d0cd-6868-41d6-8705-3fe65a72f327</webElementGuid>
   </webElementProperties>
</WebElementEntity>
