<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Last_Name</name>
   <tag></tag>
   <elementGuidId>6015a6aa-6360-4f10-b523-462fb9b3da3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;lastName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;lastName&quot;]</value>
      <webElementGuid>9c129630-cbea-47a9-bed4-0020cc51b27f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
