<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Zip</name>
   <tag></tag>
   <elementGuidId>e412ce72-628d-4849-9641-797ba920fab8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;zip&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;zip&quot;]</value>
      <webElementGuid>5ac9188c-8804-4126-ad5e-1fd9e064332f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
