<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Receipt_Time</name>
   <tag></tag>
   <elementGuidId>35da01e4-2c93-408e-911d-aa93371f25eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;receipt-time&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;receipt-time&quot;]</value>
      <webElementGuid>9c58b7f8-386e-469f-9e17-dab247f08651</webElementGuid>
   </webElementProperties>
</WebElementEntity>
