<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Address</name>
   <tag></tag>
   <elementGuidId>a4f0e2a7-45b3-4730-93bc-6ddcd25d43da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;address&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;address&quot;]</value>
      <webElementGuid>aaf00556-cf53-4566-988a-0cb20d4fbef7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
