<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Upload</name>
   <tag></tag>
   <elementGuidId>ae3b8a0e-f2b3-4e20-b408-678682585265</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;receipt-name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;receipt-name&quot;]</value>
      <webElementGuid>733fc0bf-0537-4e9b-b44b-b38da12f7d98</webElementGuid>
   </webElementProperties>
</WebElementEntity>
