<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_First_Name</name>
   <tag></tag>
   <elementGuidId>f03d5a36-f11b-4b1b-af41-f7b07f0f6028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;firstName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;firstName&quot;]</value>
      <webElementGuid>8a815b39-d14f-45c2-aaed-68b1d52236d4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
