<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_City</name>
   <tag></tag>
   <elementGuidId>a4ddcd48-297e-4af8-8d0e-e14650247a19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;city&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;city&quot;]</value>
      <webElementGuid>dce54bec-7bf3-4cd4-bee1-3319d6a4704a</webElementGuid>
   </webElementProperties>
</WebElementEntity>
