<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Submit</name>
   <tag></tag>
   <elementGuidId>d1e4e431-37bb-4b63-8833-b2f8be8a0aae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;register&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;register&quot;]</value>
      <webElementGuid>4d3b5b46-67a5-4514-914e-1485f5f1214c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
